CREATE TABLE IF NOT EXISTS flight_series (
  id INT(11) NOT NULL AUTO_INCREMENT,
  flt VARCHAR(50) NOT NULL,
  aircraft_id INT(11) NULL,
  flight_type VARCHAR(50) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  std TIME NULL,
  sta TIME NULL,
  number_of_seats INT(11) NULL,
  from_destination_id INT(11) NULL,
  from_terminal VARCHAR(100) NULL,
  to_terminal VARCHAR(100) NULL,
  via_destination_id INT(11) NULL,
  via_std TIME NULL,
  via_sta TIME NULL,
  to_destination_id INT(11) NULL,
  adult_fare DECIMAL(10, 2) NULL,
  child_fare DECIMAL(10, 2) NULL,
  infant_fare DECIMAL(10, 2) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_flt (flt),
  INDEX idx_aircraft_id (aircraft_id),
  INDEX idx_flight_type (flight_type),
  INDEX idx_start_date (start_date),
  INDEX idx_end_date (end_date),
  INDEX idx_from_destination_id (from_destination_id),
  INDEX idx_via_destination_id (via_destination_id),
  INDEX idx_to_destination_id (to_destination_id),
  FOREIGN KEY (aircraft_id) REFERENCES aircrafts(id) ON DELETE SET NULL,
  FOREIGN KEY (from_destination_id) REFERENCES destinations(id) ON DELETE SET NULL,
  FOREIGN KEY (via_destination_id) REFERENCES destinations(id) ON DELETE SET NULL,
  FOREIGN KEY (to_destination_id) REFERENCES destinations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

